version: 2
run:
  timeout: 3m
  go: "1.25"

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - gocritic
    - ineffassign
    - errcheck
    - misspell

linters-settings:
  revive:
    rules:
      - name: exported
        arguments: ["disableStutteringCheck"]
  misspell:
    locale: US

issues:
  exclude-use-default: false

output:
  sort-results: true
